# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joda_misc', '0003_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscdocument',
            name='misc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='joda_misc.MiscType', verbose_name='miscellaneous document type'),
        ),
    ]
